### PR TITLE
Ensure uv pip freeze is colorless

### LINKED ISSUE #38: uv pip freeze creates color in output
## Issue

When tox calls the `freeze` routine, uv is placing color escape sequences in the output, resulting in the dependency list containing color escape sequences and breaking the constraints text file used in subsequent steps.

## Environment

- OS: macOS Sonoma 14.3.1
- Terminal: kitty, tmux, zsh with True Color support

## Minimal example

```console
py38-mindeps: freeze> /Users/dporter/.pyenv/versions/3.11.8/bin/uv pip freeze
py38-mindeps: install_package_deps> /Users/dporter/.pyenv/versions/3.11.8/bin/uv pip install 'asyncssh<3,>=2.13.1' -c${project}/.tox/py38-mindeps/constraints.txt
error: Unexpected 'xpected '-c', '-e', '-r' or the start of a requirement at ${project}/.tox/py38-mindeps/constraints.txt:1:1

$ file .tox/py38-mindeps/constraints.txt
.tox/py38-mindeps/constraints.txt: ASCII text, with escape sequences
```

### PR DESCRIPTION
**Pull request by Stealthii**
The 'uv pip freeze' command should automatically determine whether or not to provide coloring if the output is going to a terminal or TTY with support. This is not happening in this case.

Ensuring color is always disabled for this command is a good first step to work around this issue. Fixes #38.

### CODE REVIEW

**Comment by Stealthii** [comment]
Prior to the change, the following error is encountered:
```log
error: Unexpected 'xpected '-c', '-e', '-r' or the start of a requirement at {project}/.tox/py38-mindeps/constraints.txt:1:1
```

Before:
```bash
$ file .tox/py38-mindeps/constraints.txt
.tox/py38-mindeps/constraints.txt: ASCII text, with escape sequences
```
After:
```bash
$ file .tox/py38-mindeps/constraints.txt
.tox/py38-mindeps/constraints.txt: ASCII text
```

**Review by gaborbernat — CHANGES_REQUESTED** [review]
Tests please.

**Comment by Stealthii** [comment]
Apologies, been struggling with testing this one.

* Similar tests in [tox test_python_api.py](https://github.com/tox-dev/tox/blob/4.14.1/tests/tox_env/python/test_python_api.py#L256-L279) (256-279) only test against `result.out`, which is already sanitised. `pip` is also in our instance, not installed
* Setting up `demo_pkg_inline`, even running a full install during the test, I'm stumped for a mechanism to test against the stdout of a call. I can't find any tests that do this in tox, and the two IOWrappers at `call[0][2]` are empty (I'd considered them potentially stdout/stderr)

**Comment by Stealthii** [comment]
Ah ok - I was trying to write a test for the actual output from `installed()` to validate it as pure string. I've added a test for the call arguments themselves in fab11cf.

**Review by gaborbernat — APPROVED** [review]

**Pull request merged**
