### PR TITLE
Bump uv version

### PR DESCRIPTION
**Pull request by hkad98**

### CODE REVIEW

**Comment by gaborbernat** [comment]
Why?

**Comment by Stealthii** [comment]
Minimum versions are constraints, ideally defining the lowest version providing support for the features used within a package (tox-uv).

Unless tox-uv makes exclusive use of new features provided in these newer versions (which aren't included in this PR), this isn't a good PR, only restricting further what versions of the tool are supported.

**Comment by hkad98** [comment]
@Stealthii you are right. This was just a quick PR to use the latest supported uv which can bring significant improvement in performance.

**Comment by gaborbernat** [comment]
Thing is you don't need this PR for that, if you reinstall the tool it will automatically pull it in.

**Comment by hkad98** [comment]
@gaborbernat what is the purpose of uv dependency restriction in pyproject.toml then?

**Comment by gaborbernat** [comment]
it's lower restricted, meaning we need at least this version.

**Pull request closed without merging**
